Traceback (most recent call last):
  File "/nfs/hpc/share/soloww/digital_twin/bayesian_optimizer.py", line 667, in <module>
    main()
  File "/nfs/hpc/share/soloww/digital_twin/bayesian_optimizer.py", line 655, in main
    optim.optimize()
  File "/nfs/hpc/share/soloww/digital_twin/bayesian_optimizer.py", line 127, in optimize
    samples = self.maximize(optimizer, \
  File "/nfs/hpc/share/soloww/digital_twin/bayesian_optimizer.py", line 162, in maximize
    target = self.compute_loss(stage)
  File "/nfs/hpc/share/soloww/digital_twin/bayesian_optimizer.py", line 243, in compute_loss
    true_output, model_output = self.digtwin.run_from_data(self.data_list[i], args=self.params, run_till=True)
  File "/nfs/hpc/share/soloww/digital_twin/digtwin/digital_twin.py", line 78, in run_from_data
    self.start_date = datetime.datetime.strptime(data["DATE"].iloc[0], '%Y-%m-%d')
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
